In [11]:
import pandas as pd
import gc

# Display settings
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

# ---------- Function: Full Dataset Descriptive Stats ----------
def pandas_full_describe(file_path):
    df = pd.read_csv(file_path)
    dataset_name = file_path.split("/")[-1]

    print(f"\n\n📊 Dataset: {dataset_name}")

    # --- Numeric Summary ---
    numeric_df = df.select_dtypes(include='number')
    if not numeric_df.empty:
        print("\n--- Numeric Summary ---")
        display(numeric_df.describe().round(2))
    else:
        print("⚠️ No numeric columns found.")

    # --- Categorical Summary ---
    cat_df = df.select_dtypes(include='object')
    if not cat_df.empty:
        print("\n--- Categorical Summary ---")
        summary = pd.DataFrame({
            'unique': cat_df.nunique(),
            'top': cat_df.mode().iloc[0],
            'top_count': cat_df.apply(lambda x: x.value_counts(dropna=False).iloc[0])
        })
        display(summary)
    else:
        print("⚠️ No categorical columns found.")
    
    del df
    gc.collect()

# ---------- Function: Grouped Summary ----------
def pandas_groupby_summary(file_path, group_cols, sample_n=3, max_columns=10):
    df = pd.read_csv(file_path)
    dataset_name = file_path.split("/")[-1]

    print(f"\n\n📊 Grouped Summary for: {dataset_name} | Grouped by: {group_cols}")

    if not all(col in df.columns for col in group_cols):
        print("⚠️ Skipping: One or more group columns not found.")
        return

    numeric_cols = df.select_dtypes(include='number').columns[:max_columns]
    if numeric_cols.empty:
        print("⚠️ No numeric columns to summarize.")
        return

    try:
        sample_keys = df[group_cols].drop_duplicates().head(sample_n)
    except Exception as e:
        print(f"⚠️ Error extracting group keys: {e}")
        return

    for _, row in sample_keys.iterrows():
        mask = (df[group_cols] == row.values).all(axis=1) if len(group_cols) > 1 else (df[group_cols[0]] == row.iloc[0])
        sub_df = df[mask]
        print(f"\n🔹 Group: {tuple(row.values)} — {len(sub_df)} rows")
        display(sub_df[numeric_cols].describe().round(2))

    del df
    gc.collect()

# ---------- Dataset Configuration ----------
dataset_config = [
    {
        "file": "C:/Users/unnat/OneDrive/Desktop/RA/Task_04_Descriptive_Stats/data/period_03/2024_fb_ads_president_scored_anon.csv",
        "group_cols": ["page_id", "ad_id"]  # as per instructions
    },
    {
        "file": "C:/Users/unnat/OneDrive/Desktop/RA/Task_04_Descriptive_Stats/data/period_03/2024_fb_posts_president_scored_anon.csv",
        "group_cols": ["Page Admin Top Country"]  # logical aggregation
    },
    {
        "file": "C:/Users/unnat/OneDrive/Desktop/RA/Task_04_Descriptive_Stats/data/period_03/2024_tw_posts_president_scored_anon.csv",
        "group_cols": ["source"]  # Twitter platform
    }
]

# ---------- Run All Analyses ----------
for config in dataset_config:
    pandas_full_describe(config["file"])
    pandas_groupby_summary(config["file"], config["group_cols"])

📊 Dataset: 2024_fb_ads_president_scored_anon.csv

--- Numeric Summary ---

,estimated_audience_size,estimated_impressions,estimated_spend,scam_illuminating,election_integrity_Truth_illuminating,advocacy_msg_type_illuminating,issue_msg_type_illuminating,attack_msg_type_illuminating,image_msg_type_illuminating,cta_msg_type_illuminating,engagement_cta_subtype_illuminating,fundraising_cta_subtype_illuminating,voting_cta_subtype_illuminating,covid_topic_illuminating,economy_topic_illuminating,education_topic_illuminating,environment_topic_illuminating,foreign_policy_topic_illuminating,governance_topic_illuminating,health_topic_illuminating,immigration_topic_illuminating,lgbtq_issues_topic_illuminating,military_topic_illuminating,race_and_ethnicity_topic_illuminating,safety_topic_illuminating,social_and_cultural_topic_illuminating,technology_and_privacy_topic_illuminating,womens_issue_topic_illuminating,incivility_illuminating,freefair_illuminating,fraud_illuminating
count,246745.00,246745.00,246745.00,246745.00,246745.00,246745.00,246745.00,246745.00,246745.00,246745.00,246745.00,246745.00,246745.00,246745.00,246745.00,246745.00,246745.00,246745.00,246745.00,246745.00,246745.00,246745.00,246745.00,246745.00,246745.00,246745.00,246745.00,246745.00,246745.00,246745.00,246745.00
mean,556462.86,45601.53,1061.29,0.07,0.05,0.55,0.38,0.27,0.22,0.57,0.12,0.23,0.14,0.02,0.12,0.01,0.02,0.01,0.03,0.11,0.03,0.00,0.00,0.01,0.03,0.11,0.00,0.08,0.19,0.01,0.00
std,409864.76,136790.77,4992.56,0.26,0.22,0.50,0.49,0.44,0.42,0.49,0.33,0.42,0.35,0.16,0.33,0.12,0.14,0.07,0.16,0.31,0.18,0.06,0.05,0.11,0.18,0.31,0.03,0.27,0.39,0.08,0.05
min,0.00,499.00,49.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
25%,75000.00,499.00,49.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
50%,300000.00,3499.00,49.00,0.00,0.00,1.00,0.00,0.00,0.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
75%,1000001.00,22499.00,449.00,0.00,0.00,1.00,1.00,1.00,0.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
max,1000001.00,1000000.00,474999.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00

--- Categorical Summary ---

,unique,top,top_count
page_id,4475,4d66f5853f0365dba032a87704a634f023d15babde973b...,55503
ad_id,246745,0000a88a64484883df6ca1fabd357e4c5950e443123ce3...,1
ad_creation_time,547,2024-10-27,8619
bylines,3790,HARRIS FOR PRESIDENT,49788
currency,18,USD,246599
delivery_by_region,141122,{},30989
demographic_distribution,215622,{},30989
publisher_platforms,9,"['facebook', 'instagram']",214434
illuminating_scored_message,26338,e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b93...,5972
illuminating_mentions,278,[],73205

📊 Grouped Summary for: 2024_fb_ads_president_scored_anon.csv | Grouped by: ['page_id', 'ad_id']

🔹 Group: ('4ff23a48b53d988df50ddfebb0e442a984ab8f94e874ef9b9cb34394e0c5d230', '0ddb025b8544e2d58e6977ad417e742a52522b3e1fc1c9d9b61c57148f8d72fc') — 1 rows

,estimated_audience_size,estimated_impressions,estimated_spend,scam_illuminating,election_integrity_Truth_illuminating,advocacy_msg_type_illuminating,issue_msg_type_illuminating,attack_msg_type_illuminating,image_msg_type_illuminating,cta_msg_type_illuminating
count,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
mean,30000.0,47499.0,249.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,30000.0,47499.0,249.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
25%,30000.0,47499.0,249.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
50%,30000.0,47499.0,249.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
75%,30000.0,47499.0,249.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
max,30000.0,47499.0,249.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0

🔹 Group: ('4ff23a48b53d988df50ddfebb0e442a984ab8f94e874ef9b9cb34394e0c5d230', '86229868e6bde3661724fe02da93504bb4fb5da8c2550d7b7cf193c687e89fa6') — 1 rows

,estimated_audience_size,estimated_impressions,estimated_spend,scam_illuminating,election_integrity_Truth_illuminating,advocacy_msg_type_illuminating,issue_msg_type_illuminating,attack_msg_type_illuminating,image_msg_type_illuminating,cta_msg_type_illuminating
count,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
mean,75000.0,22499.0,49.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,75000.0,22499.0,49.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
25%,75000.0,22499.0,49.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
50%,75000.0,22499.0,49.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
75%,75000.0,22499.0,49.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
max,75000.0,22499.0,49.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0

🔹 Group: ('4ff23a48b53d988df50ddfebb0e442a984ab8f94e874ef9b9cb34394e0c5d230', '07b5aefc27e872e971f793e49aac38496fa62e484f3928e2b6a2b6e3e08cac8d') — 1 rows

,estimated_audience_size,estimated_impressions,estimated_spend,scam_illuminating,election_integrity_Truth_illuminating,advocacy_msg_type_illuminating,issue_msg_type_illuminating,attack_msg_type_illuminating,image_msg_type_illuminating,cta_msg_type_illuminating
count,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
mean,75000.0,32499.0,149.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,75000.0,32499.0,149.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
25%,75000.0,32499.0,149.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
50%,75000.0,32499.0,149.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
75%,75000.0,32499.0,149.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
max,75000.0,32499.0,149.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0

📊 Dataset: 2024_fb_posts_president_scored_anon.csv

--- Numeric Summary ---

,Likes,Comments,Shares,Love,Wow,Haha,Sad,Angry,Care,Post Views,Total Views,Total Views For All Crossposts,Sponsor Id,Sponsor Name,Sponsor Category,Overperforming Score,illuminating_scored_messageelection_integrity_Truth_illuminating,advocacy_msg_type_illuminating,issue_msg_type_illuminating,attack_msg_type_illuminating,image_msg_type_illuminating,cta_msg_type_illuminating,engagement_cta_subtype_illuminating,fundraising_cta_subtype_illuminating,voting_cta_subtype_illuminating,covid_topic_illuminating,economy_topic_illuminating,education_topic_illuminating,environment_topic_illuminating,foreign_policy_topic_illuminating,governance_topic_illuminating,health_topic_illuminating,immigration_topic_illuminating,lgbtq_issues_topic_illuminating,military_topic_illuminating,race_and_ethnicity_topic_illuminating,safety_topic_illuminating,social_and_cultural_topic_illuminating,technology_and_privacy_topic_illuminating,womens_issue_topic_illuminating,incivility_illuminating,scam_illuminating,freefair_illuminating,fraud_illuminating
count,19009.00,19009.00,19009.00,19009.00,19009.00,19009.00,19009.00,19009.00,19009.00,16544.00,16544.00,16544.00,0.0,0.0,0.0,16544.00,0.0,19009.00,19009.00,19009.00,19009.00,19009.00,19009.00,19009.00,19009.00,19009.00,19009.00,19009.00,19009.00,19009.00,19009.00,19009.00,19009.00,19009.00,19009.00,19009.00,19009.00,19009.00,19009.00,19009.00,19009.00,18060.00,19009.00,19009.00
mean,2377.70,901.58,320.54,413.88,5.87,105.72,10.17,20.06,34.93,6485.06,7461.85,3555.94,NaN,NaN,NaN,-2.74,NaN,0.55,0.46,0.22,0.15,0.13,0.09,0.02,0.02,0.05,0.09,0.01,0.02,0.04,0.03,0.05,0.04,0.00,0.01,0.02,0.03,0.06,0.00,0.03,0.13,0.02,0.00,0.01
std,11253.47,3681.98,1722.16,3730.94,52.95,942.03,418.33,156.02,790.10,90392.96,95976.28,88094.05,NaN,NaN,NaN,7.81,NaN,0.50,0.50,0.41,0.36,0.34,0.29,0.13,0.15,0.22,0.29,0.12,0.15,0.19,0.17,0.22,0.20,0.06,0.07,0.15,0.18,0.24,0.05,0.16,0.33,0.14,0.05,0.09
min,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,-198.75,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
25%,31.00,8.00,3.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,-3.87,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
50%,139.00,48.00,21.00,4.00,1.00,2.00,0.00,1.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,-1.62,NaN,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
75%,738.00,354.00,102.00,70.00,3.00,29.00,2.00,9.00,6.00,0.00,0.00,0.00,NaN,NaN,NaN,1.16,NaN,1.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
max,351979.00,93872.00,76150.00,244482.00,4345.00,99276.00,56111.00,11814.00,85236.00,4276477.00,4462155.00,4499458.00,NaN,NaN,NaN,246.78,NaN,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00

--- Categorical Summary ---

,unique,top,top_count
Facebook_Id,21,32fc18da91029ff09bf74fe9887eace6b5d2145809d583...,9013
post_id,19009,0001e4a1dbadf84f0f43719972b60597cc79f1908bf601...,1
Page Category,6,PERSON,9453
Page Admin Top Country,1,US,16280
Post Created,18951,2023-11-14 11:11:44 EST,2
Post Created Date,425,2024-10-31,103
Post Created Time,16102,17:30:01,7
Type,9,Link,7404
Total Interactions,5665,15,115
Video Share Status,3,owned,15738
Is Video Owner?,3,-,13280
Video Length,774,00:00:30,15738

📊 Grouped Summary for: 2024_fb_posts_president_scored_anon.csv | Grouped by: ['Page Admin Top Country']

🔹 Group: ('US',) — 16280 rows

,Likes,Comments,Shares,Love,Wow,Haha,Sad,Angry,Care,Post Views
count,16280.00,16280.00,16280.00,16280.00,16280.00,16280.00,16280.00,16280.00,16280.00,16280.00
mean,1478.92,695.04,226.16,483.17,6.85,123.41,11.87,23.41,40.78,6588.37
std,8224.84,3174.51,1378.69,4027.41,57.15,1016.87,452.01,168.36,853.63,91119.30
min,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
25%,26.00,7.00,3.00,0.00,0.00,1.00,0.00,0.00,0.00,0.00
50%,107.00,37.00,17.00,11.00,1.00,5.00,0.00,2.00,1.00,0.00
75%,566.25,283.00,78.00,95.00,4.00,46.00,2.00,12.00,8.00,0.00
max,315973.00,93872.00,76150.00,244482.00,4345.00,99276.00,56111.00,11814.00,85236.00,4276477.00

🔹 Group: (nan,) — 0 rows

       Likes  Comments  Shares  Love  Wow  Haha  Sad  Angry  Care  Post Views
count    0.0       0.0     0.0   0.0  0.0   0.0  0.0    0.0   0.0         0.0
mean     NaN       NaN     NaN   NaN  NaN   NaN  NaN    NaN   NaN         NaN
std      NaN       NaN     NaN   NaN  NaN   NaN  NaN    NaN   NaN         NaN
min      NaN       NaN     NaN   NaN  NaN   NaN  NaN    NaN   NaN         NaN
25%      NaN       NaN     NaN   NaN  NaN   NaN  NaN    NaN   NaN         NaN
50%      NaN       NaN     NaN   NaN  NaN   NaN  NaN    NaN   NaN         NaN
75%      NaN       NaN     NaN   NaN  NaN   NaN  NaN    NaN   NaN         NaN
max      NaN       NaN     NaN   NaN  NaN   NaN  NaN    NaN   NaN         NaN

📊 Dataset: 2024_tw_posts_president_scored_anon.csv

--- Numeric Summary ---

,retweetCount,replyCount,likeCount,quoteCount,viewCount,bookmarkCount,quoteId,inReplyToId,election_integrity_Truth_illuminating,advocacy_msg_type_illuminating,issue_msg_type_illuminating,attack_msg_type_illuminating,image_msg_type_illuminating,cta_msg_type_illuminating,engagement_cta_subtype_illuminating,fundraising_cta_subtype_illuminating,voting_cta_subtype_illuminating,covid_topic_illuminating,economy_topic_illuminating,education_topic_illuminating,environment_topic_illuminating,foreign_policy_topic_illuminating,governance_topic_illuminating,health_topic_illuminating,immigration_topic_illuminating,lgbtq_issues_topic_illuminating,military_topic_illuminating,race_and_ethnicity_topic_illuminating,safety_topic_illuminating,social_and_cultural_topic_illuminating,technology_and_privacy_topic_illuminating,womens_issue_topic_illuminating,incivility_illuminating,scam_illuminating,freefair_illuminating,fraud_illuminating
count,27304.00,27304.00,27304.00,27304.00,2.730400e+04,27304.00,3.287000e+03,3.345000e+03,26034.00,26034.00,26034.00,26034.00,26034.00,26034.00,26034.00,26034.00,26034.00,26034.00,26034.00,26034.00,26034.00,26034.00,26034.00,26034.00,26034.00,26034.00,26034.00,26034.00,26034.00,26034.00,26034.00,26034.00,26034.00,26034.00,27304.00,27304.00
mean,1322.06,1063.79,6913.69,128.08,5.070847e+05,136.21,1.764298e+18,1.758286e+18,0.04,0.56,0.51,0.31,0.23,0.11,0.07,0.01,0.02,0.01,0.16,0.02,0.03,0.04,0.02,0.06,0.07,0.00,0.01,0.02,0.04,0.05,0.00,0.02,0.18,0.01,0.00,0.00
std,3405.00,3174.98,21590.31,1131.53,3.212174e+06,712.58,6.894687e+16,4.361197e+16,0.19,0.50,0.50,0.46,0.42,0.31,0.25,0.09,0.13,0.09,0.37,0.13,0.17,0.20,0.15,0.23,0.25,0.06,0.10,0.12,0.19,0.22,0.05,0.15,0.38,0.11,0.04,0.05
min,0.00,0.00,0.00,0.00,5.000000e+00,0.00,7.912639e+17,1.240067e+18,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
25%,84.00,43.00,393.00,5.00,2.785275e+04,4.00,1.726459e+18,1.726801e+18,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
50%,333.00,131.00,1406.00,17.00,7.094200e+04,21.00,1.756496e+18,1.746641e+18,0.00,1.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
75%,1071.00,501.25,5010.00,69.00,3.036630e+05,76.00,1.816599e+18,1.789226e+18,0.00,1.00,1.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
max,144615.00,121270.00,915221.00,123320.00,3.335028e+08,42693.00,1.853576e+18,1.853531e+18,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00

--- Categorical Summary ---

,unique,top,top_count
id,27304,0000635d0c9e7bdf89dfc13811d080dbffac5489459435...,1
url,27304,0000179c6b90798f167528aaaaf67886a975ea68af78f4...,1
source,14,Twitter Web App,14930
createdAt,27014,2023-10-06 04:55:21,4
lang,12,en,27281
month_year,15,2024-10,3586
illuminating_scored_message,27136,36cb7d55fcf85362ca03f624c2f574f1f55f89db559b17...,21

📊 Grouped Summary for: 2024_tw_posts_president_scored_anon.csv | Grouped by: ['source']

🔹 Group: ('Twitter for iPhone',) — 8494 rows

,retweetCount,replyCount,likeCount,quoteCount,viewCount,bookmarkCount,quoteId,inReplyToId,election_integrity_Truth_illuminating,advocacy_msg_type_illuminating
count,8494.00,8494.00,8494.00,8494.00,8494.00,8494.00,1.856000e+03,1.798000e+03,8168.00,8168.0
mean,612.62,289.79,3741.96,43.78,245622.12,69.80,1.750620e+18,1.748088e+18,0.04,0.5
std,2155.93,1035.97,15956.71,190.69,954516.49,402.96,6.502825e+16,3.456482e+16,0.20,0.5
min,0.00,0.00,0.00,0.00,9.00,0.00,7.957424e+17,1.240067e+18,0.00,0.0
25%,16.00,11.00,97.00,1.00,11731.75,1.00,1.721980e+18,1.726772e+18,0.00,0.0
50%,82.50,57.00,413.00,6.00,35590.50,5.00,1.741540e+18,1.737525e+18,0.00,0.0
75%,383.00,202.75,2030.75,26.00,141409.00,28.00,1.787349e+18,1.764762e+18,0.00,1.0
max,67113.00,30215.00,588065.00,6552.00,31294362.00,22901.00,1.853576e+18,1.853134e+18,1.00,1.0

🔹 Group: ('Twitter Web App',) — 14930 rows

,retweetCount,replyCount,likeCount,quoteCount,viewCount,bookmarkCount,quoteId,inReplyToId,election_integrity_Truth_illuminating,advocacy_msg_type_illuminating
count,14930.00,14930.00,14930.00,14930.00,1.493000e+04,14930.00,1.390000e+03,1.482000e+03,14199.00,14199.00
mean,1317.11,719.20,6669.75,120.05,4.740312e+05,154.31,1.782319e+18,1.771888e+18,0.04,0.58
std,3571.55,2689.14,22475.18,1464.57,3.966176e+06,843.42,7.067792e+16,4.978459e+16,0.19,0.49
min,0.00,0.00,0.00,0.00,5.000000e+00,0.00,7.912639e+17,1.478769e+18,0.00,0.00
25%,188.00,60.00,694.00,7.00,3.447075e+04,10.00,1.743129e+18,1.728961e+18,0.00,0.00
50%,418.00,132.50,1660.00,19.00,7.161300e+04,28.00,1.799066e+18,1.771728e+18,0.00,1.00
75%,1021.00,363.00,4505.50,59.00,2.364675e+05,86.00,1.827992e+18,1.822177e+18,0.00,1.00
max,144615.00,121270.00,915221.00,123320.00,3.335028e+08,42693.00,1.853110e+18,1.853531e+18,1.00,1.00

🔹 Group: ('Sprout Social',) — 2933 rows

,retweetCount,replyCount,likeCount,quoteCount,viewCount,bookmarkCount,quoteId,inReplyToId,election_integrity_Truth_illuminating,advocacy_msg_type_illuminating
count,2933.00,2933.00,2933.00,2933.00,2933.00,2933.00,2.900000e+01,0.0,2769.00,2769.00
mean,3524.79,5186.27,18173.41,426.12,1501097.31,230.80,1.778639e+18,NaN,0.03,0.68
std,4584.68,5804.89,28810.23,855.02,3432962.00,581.85,3.237946e+16,NaN,0.18,0.47
min,13.00,12.00,60.00,0.00,2647.00,0.00,1.696504e+18,NaN,0.00,0.00
25%,719.00,1382.00,3708.00,75.00,286290.00,24.00,1.758534e+18,NaN,0.00,0.00
50%,2198.00,3361.00,9480.00,195.00,659392.00,74.00,1.782752e+18,NaN,0.00,1.00
75%,4671.00,6920.00,21318.00,454.00,1467341.00,204.00,1.801976e+18,NaN,0.00,1.00
max,80331.00,60598.00,423537.00,17200.00,76522204.00,13271.00,1.851262e+18,NaN,1.00,1.00

In [9]:
files = [
    "C:/Users/unnat/OneDrive/Desktop/RA/Task_04_Descriptive_Stats/data/period_03/2024_fb_ads_president_scored_anon.csv",
    "C:/Users/unnat/OneDrive/Desktop/RA/Task_04_Descriptive_Stats/data/period_03/2024_fb_posts_president_scored_anon.csv",
    "C:/Users/unnat/OneDrive/Desktop/RA/Task_04_Descriptive_Stats/data/period_03/2024_tw_posts_president_scored_anon.csv"
]

for file_path in files:
    df = pd.read_csv(file_path, nrows=1)  # Only load the header row
    print(f"\n📄 Columns in: {file_path.split('/')[-1]}")
    print(df.columns.tolist())

📄 Columns in: 2024_fb_ads_president_scored_anon.csv
['page_id', 'ad_id', 'ad_creation_time', 'bylines', 'currency', 'delivery_by_region', 'demographic_distribution', 'estimated_audience_size', 'estimated_impressions', 'estimated_spend', 'publisher_platforms', 'illuminating_scored_message', 'illuminating_mentions', 'scam_illuminating', 'election_integrity_Truth_illuminating', 'advocacy_msg_type_illuminating', 'issue_msg_type_illuminating', 'attack_msg_type_illuminating', 'image_msg_type_illuminating', 'cta_msg_type_illuminating', 'engagement_cta_subtype_illuminating', 'fundraising_cta_subtype_illuminating', 'voting_cta_subtype_illuminating', 'covid_topic_illuminating', 'economy_topic_illuminating', 'education_topic_illuminating', 'environment_topic_illuminating', 'foreign_policy_topic_illuminating', 'governance_topic_illuminating', 'health_topic_illuminating', 'immigration_topic_illuminating', 'lgbtq_issues_topic_illuminating', 'military_topic_illuminating', 'race_and_ethnicity_topic_illuminating', 'safety_topic_illuminating', 'social_and_cultural_topic_illuminating', 'technology_and_privacy_topic_illuminating', 'womens_issue_topic_illuminating', 'incivility_illuminating', 'freefair_illuminating', 'fraud_illuminating']

📄 Columns in: 2024_fb_posts_president_scored_anon.csv
['Facebook_Id', 'post_id', 'Page Category', 'Page Admin Top Country', 'Post Created', 'Post Created Date', 'Post Created Time', 'Type', 'Total Interactions', 'Likes', 'Comments', 'Shares', 'Love', 'Wow', 'Haha', 'Sad', 'Angry', 'Care', 'Video Share Status', 'Is Video Owner?', 'Post Views', 'Total Views', 'Total Views For All Crossposts', 'Video Length', 'Sponsor Id', 'Sponsor Name', 'Sponsor Category', 'Overperforming Score', 'illuminating_scored_messageelection_integrity_Truth_illuminating', 'advocacy_msg_type_illuminating', 'issue_msg_type_illuminating', 'attack_msg_type_illuminating', 'image_msg_type_illuminating', 'cta_msg_type_illuminating', 'engagement_cta_subtype_illuminating', 'fundraising_cta_subtype_illuminating', 'voting_cta_subtype_illuminating', 'covid_topic_illuminating', 'economy_topic_illuminating', 'education_topic_illuminating', 'environment_topic_illuminating', 'foreign_policy_topic_illuminating', 'governance_topic_illuminating', 'health_topic_illuminating', 'immigration_topic_illuminating', 'lgbtq_issues_topic_illuminating', 'military_topic_illuminating', 'race_and_ethnicity_topic_illuminating', 'safety_topic_illuminating', 'social_and_cultural_topic_illuminating', 'technology_and_privacy_topic_illuminating', 'womens_issue_topic_illuminating', 'incivility_illuminating', 'scam_illuminating', 'freefair_illuminating', 'fraud_illuminating']

📄 Columns in: 2024_tw_posts_president_scored_anon.csv
['id', 'url', 'source', 'retweetCount', 'replyCount', 'likeCount', 'quoteCount', 'viewCount', 'createdAt', 'lang', 'bookmarkCount', 'isReply', 'isRetweet', 'isQuote', 'isConversationControlled', 'quoteId', 'inReplyToId', 'month_year', 'illuminating_scored_message', 'election_integrity_Truth_illuminating', 'advocacy_msg_type_illuminating', 'issue_msg_type_illuminating', 'attack_msg_type_illuminating', 'image_msg_type_illuminating', 'cta_msg_type_illuminating', 'engagement_cta_subtype_illuminating', 'fundraising_cta_subtype_illuminating', 'voting_cta_subtype_illuminating', 'covid_topic_illuminating', 'economy_topic_illuminating', 'education_topic_illuminating', 'environment_topic_illuminating', 'foreign_policy_topic_illuminating', 'governance_topic_illuminating', 'health_topic_illuminating', 'immigration_topic_illuminating', 'lgbtq_issues_topic_illuminating', 'military_topic_illuminating', 'race_and_ethnicity_topic_illuminating', 'safety_topic_illuminating', 'social_and_cultural_topic_illuminating', 'technology_and_privacy_topic_illuminating', 'womens_issue_topic_illuminating', 'incivility_illuminating', 'scam_illuminating', 'freefair_illuminating', 'fraud_illuminating']